# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '7cb11741-f734-48ae-959b-44009ae8c9cc'
  imageRepository: 'dotnet/core/aspnet'
  containerRegistry: 'andreandrade.azurecr.io'
  dockerfilePath: 'image/Dockerfile'
  tag: '$(Build.BuildId)'
  system.debug: true

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    command: login
    containerRegistry: $(dockerRegistryServiceConnection)

- task: DownloadSecureFile@1
  name: privateCert
  inputs:
    secureFile: delegation.crt
- script: |
    mkdir -p $(DOCKER_CONFIG)/trust/private
    cp $(privateCert.secureFilePath) $(DOCKER_CONFIG)/trust/private

- task: DownloadSecureFile@1
  name: privateKey
  inputs:
    secureFile: delegation.key
- script: |
    cp $(privateKey.secureFilePath) $(DOCKER_CONFIG)/trust/private
    sudo chmod 600 $(DOCKER_CONFIG)/trust/private/delegation.key

- task: DownloadSecureFile@1
  name: privateKeyTarget
  inputs:
    secureFile: 485d16e047e90fedb2d83444b52fa0f4239fe03f618e466ea4974ac71f0d31f9.key
- script: |
    cp $(privateKeyTarget.secureFilePath) $(DOCKER_CONFIG)/trust/private
    sudo chmod 600 $(DOCKER_CONFIG)/trust/private/485d16e047e90fedb2d83444b52fa0f4239fe03f618e466ea4974ac71f0d31f9.key

- task: Docker@2
  inputs:
    command: build
    Dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    tags: |
      $(tag)
#    arguments: '--disable-content-trust=false'

- bash: |
    docker trust key load $(DOCKER_CONFIG)/trust/private/485d16e047e90fedb2d83444b52fa0f4239fe03f618e466ea4974ac71f0d31f9.key --name targets
    docker trust key load $(DOCKER_CONFIG)/trust/private/delegation.key --name test-role
    docker trust signer add --key $(DOCKER_CONFIG)/trust/private/delegation.crt test-role $(containerRegistry)/$(imageRepository)
    docker trust sign $(containerRegistry)/$(imageRepository):$(Build.BuildId)
  env:
    DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: $(DOCKER_CONTET_PASSPHRASE)
    DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE: $(DOCKER_CONTET_PASSPHRASE)


- task: Docker@2
  inputs: 
    command: push
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    tags: |
      $(tag)
#    arguments: '--disable-content-trust=false'
  env:
    DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: $(DOCKER_CONTET_PASSPHRASE)
    DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE: $(DOCKER_CONTET_PASSPHRASE)

- task: CmdLine@2
  inputs:
        script: |
          docker trust inspect --pretty $(containerRegistry)/$(imageRepository)
          docker trust inspect --pretty $(containerRegistry)/$(imageRepository):$(Build.BuildId)